### ISSUE TITLE
Device-Tree(s) Incomplete

### ISSUE THREAD

**Issue by Madhav-Sheth** [NusantaraROM-Devices/device_xiaomi_miatoll#1]
[This Repo,](https://github.com/NusantaraROM-Devices/device_xiaomi_miatoll/blob/26953e243848423b946a5d15263794036662fae4/nad.dependencies#L5) Which is needed for building is private. Any idea on when will it be public?

**Comment by Edgars-Cirulis** [comment]
Sorry, I use Apache-2.0 license for private source. Due community autitude It won't be public.
